//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Boolean @__actions_default_in_InteractUI;
        
        public static SteamVR_Action_Boolean @__actions_default_in_Teleport;
        
        public static SteamVR_Action_Vector2 @__actions_default_in_ControlTime;
        
        public static SteamVR_Action_Boolean @__actions_default_in_EmitSound;
        
        public static SteamVR_Action_Pose @__actions_default_in_Pose;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.@__actions_default_in_InteractUI.Initialize();
            SteamVR_Input.@__actions_default_in_Teleport.Initialize();
            SteamVR_Input.@__actions_default_in_ControlTime.Initialize();
            SteamVR_Input.@__actions_default_in_EmitSound.Initialize();
            SteamVR_Input.@__actions_default_in_Pose.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.@__actions_default_in_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_InteractUI")));
            Valve.VR.SteamVR_Input.@__actions_default_in_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_Teleport")));
            Valve.VR.SteamVR_Input.@__actions_default_in_ControlTime = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_default_in_ControlTime")));
            Valve.VR.SteamVR_Input.@__actions_default_in_EmitSound = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_EmitSound")));
            Valve.VR.SteamVR_Input.@__actions_default_in_Pose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_default_in_Pose")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.@__actions_default_in_ControlTime,
                    Valve.VR.SteamVR_Input.@__actions_default_in_EmitSound,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.@__actions_default_in_ControlTime,
                    Valve.VR.SteamVR_Input.@__actions_default_in_EmitSound,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.@__actions_default_in_EmitSound};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_ControlTime};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.@__actions_default_in_ControlTime,
                    Valve.VR.SteamVR_Input.@__actions_default_in_EmitSound};
        }
    }
}
